version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - '6379:6379'

  backend:
    container_name: back
    build: ../backend/foodgram
    image: oxdium/foodgram_backend:latest
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env

  frontend:
    container_name: front
    build: ../frontend
    image: oxdium/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend

  celery-worker:
    container_name: celery-worker
    image: oxdium/foodgram:latest
    volumes:
      - celery_volume:/usr/src/app/
    depends_on:
      - redis
      - backend
    command: celery -A foodgram worker --loglevel=info -P eventlet
    env_file:
      - ./.env

  celery-beat:
    container_name: celery-beat
    image: oxdium/foodgram:latest
    volumes:
      - celery_volume:/usr/src/app/
    depends_on:
      - redis
      - backend
    command: celery -A foodgram beat -l info
    env_file:
      - ./.env

  celery-flower:
    container_name: celery-flower
    image: oxdium/foodgram:latest
    volumes:
      - celery_volume:/usr/src/app/
    depends_on:
      - redis
      - backend
    ports:
      - 5555:5555
    command: celery -A foodgram flower worker --url_prefix=flower --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
    env_file:
      - ./.env

volumes:
  db_volume:
  static_volume:
  media_volume:
  celery_volume: