version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  # TODO: add celery

  backend:
    container_name: back
    build: ../backend/foodgram
    image: oxdium/foodgram:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env

  frontend:
    container_name: front
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend

  redis:
    container_name: redis
    image: redis
    command: redis-server
    ports:
      - '14000:6379'

volumes:
  db_volume:
  static_volume:
  media_volume:
