# Generated by Django 4.1.8 on 2023-04-23 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количесвто 1'), django.core.validators.MaxValueValidator(5000, message='Максимальное количество 5000')], verbose_name='Количество'),
        ),
        migrations.AddConstraint(
            model_name='amountingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient', violation_error_message='Повторное добавление ингредиента'),
        ),
    ]
