# Generated by Django 4.1.8 on 2023-04-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredient',
            old_name='year',
            new_name='amount',
        ),
    ]
