# Generated by Django 4.1.8 on 2023-04-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_follow_unique_user_following_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
    ]
